server:
  port: 8084

seata:
  tx-service-group: hefei
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: 24ae8979-b6a4-4d62-859d-e9c77e1acac8
      username: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
      namespace: 24ae8979-b6a4-4d62-859d-e9c77e1acac8
      data-id: seataServer.properties

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8089