server:
  port: 8079
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8079/auth-service/rsa/publicKey' #配置RSA的公钥访问地址

  cloud:
    gateway:
      routes:     #配置gateway路由规则
        - id: user-route
          uri: lb://upstage-service
          predicates:
            - Path=/upstage-service/**
          filters:
            - StripPrefix=1
        - id: prod-route
          uri: lb://prod-service
          predicates:
            - Path=/prod-service/**
          filters:
            - StripPrefix=1
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
        - id: file-route
          uri: lb://file-service
          predicates:
            - Path=/file-service/**
          filters:
            - StripPrefix=1
        - id: business-route
          uri: lb://business-service
          predicates:
            - Path=/business-service/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 5bf17891-cbb5-4379-87c7-328de242f02d
        username: nacos
        password: nacos


secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/*/v2/api-docs"
      - "/*/*.js"
      - "/*/*.css"
      - "/*/*.png"
      - "/*/*.ico"
      - "/webjars/**"
      - "/actuator/**"
      - "/upstage-service/admin/code"
      - "/upstage-service/admin/login"
      - "/auth-service/rsa/publicKey"
      - "/upstage-service/excel/download"
      - "/file-service/preview/**"
      - "/file-service/file/download"
      - "/business-service/excel/download/**"




