server:
  port: 8082

#springBoot默认的日志级别是info，info的级别大于bebug,feign的debug日志级别就不会输出
logging:
  level:
    com.jxm.prod.feign: debug


spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8089
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  #必须添加，否则knife4j无法捕捉该服务的接口信息


feign:
  sentinel:
    enabled: true
  client:
    config:
      user-service:
        loggerLevel: BASIC
        #连接超时时间，即网络连接时间
        connectTimeout: 5000
        #请求处理读取超时时间
        readTimeout: 3000
seata:
  tx-service-group: hefei
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: 5bf17891-cbb5-4379-87c7-328de242f02d
      username: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
      namespace: 5bf17891-cbb5-4379-87c7-328de242f02d
      data-id: seataServer.properties
